version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "vril-labs"
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
      - "automated"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      production-dependencies:
        patterns:
          - "*"
        dependency-type: "production"
      development-dependencies:
        patterns:
          - "*"
        dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    reviewers:
      - "vril-labs"
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
