name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: '30 1 * * 6'
  push:
    branches: ["master"]

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40
        with:
          egress-policy: audit

      - name: "Checkout code"
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@e8e61e86ea0a152be84d03729c02a7300065c17d
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: "Upload artifact"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@c16c0f3f2812ec4bb3750a5ed64873fe2ce0fbef
        with:
          sarif_file: results.sarif
